; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only.

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A721E15C-10F3-4F19-BA4A-0892CBA4768A}
AppName=AccuBooks
AppVersion=1.0.0
;AppVerName={cm:NameAndVersion,AccuBooks,1.0.0}
DefaultDirName={autopf}\AccuBooks
UninstallDisplayIcon={app}\accubooks.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.
; This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer.
;SetupArchitecture=x64
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\coding\AccuBooks\installer
OutputBaseFilename=AccuBooks
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\coding\AccuBooks\build\windows\x64\runner\Release\accubooks.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\coding\AccuBooks\build\windows\x64\runner\Release\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\coding\AccuBooks\build\windows\x64\runner\Release\pdfium.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\coding\AccuBooks\build\windows\x64\runner\Release\printing_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\coding\AccuBooks\build\windows\x64\runner\Release\sqlite3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\coding\AccuBooks\build\windows\x64\runner\Release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files.

[Icons]
Name: "{autoprograms}\AccuBooks"; Filename: "{app}\accubooks.exe"
Name: "{autodesktop}\AccuBooks"; Filename: "{app}\accubooks.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\accubooks.exe"; Description: "{cm:LaunchProgram,AccuBooks}"; Flags: nowait postinstall skipifsilent

